[package]
name = "validator"
version = "0.1.0"
authors = ["Abacus Team"]
edition = "2021"

[dependencies]
tokio = { version = "1.0.1", features = ["rt", "macros"] }
config = "0.10"
serde = "1.0.120"
serde_json = { version = "1.0.61", default-features = false }
log = "0.4"
ethers = { git = "https://github.com/gakonst/ethers-rs", branch = "master" }
thiserror = { version = "1.0.22", default-features = false }
async-trait = { version = "0.1.42", default-features = false }
futures-util = "0.3.12"
eyre = "0.6"
color-eyre = { version = "0.6", optional = true }
oneline-eyre = { version = "0.1", optional = true }
tracing = "0.1"
tracing-futures = "0.2"
tracing-subscriber = "0.3"
rocksdb = { git = "https://github.com/rust-rocksdb/rust-rocksdb" }

abacus-core = { path = "../../abacus-core" }
abacus-base = { path = "../../abacus-base" }
abacus-ethereum = { path = "../../chains/abacus-ethereum" }
paste = "1.0.5"

[dev-dependencies]
tokio-test = "0.4.0"
abacus-test = { path = "../../abacus-test" }
prometheus = "0.12"

[features]
default = ["color-eyre"]
oneline-outputs = ["oneline-eyre"]
