apiVersion: batch/v1
kind: CronJob
metadata:
  name: helloworld-kathy
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: helloworld-kathy
            image: gcr.io/abacus-labs-dev/abacus-monorepo:trevor-testing
            imagePullPolicy: IfNotPresent
            command:
            - ./node_modules/.bin/ts-node
            - ./typescript/infra/scripts/helloworld/kathy.ts
            - -e
            - {{ .Values.abacus.runEnv }}
            envFrom:
            - secretRef:
                name: {{ include "abacus-agent.fullname" . }}-secret
