apiVersion: batch/v1
kind: CronJob
metadata:
  name: helloworld-kathy
spec:
  schedule: "*/6 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: helloworld-kathy
            image: gcr.io/abacus-labs-dev/abacus-monorepo@sha256:288dc1def387b27c98817b34487d568b39c8b1ec5bebd475ab7c9606c8adcc67
            imagePullPolicy: IfNotPresent
            command:
            - ./node_modules/.bin/ts-node
            - ./typescript/infra/scripts/helloworld/kathy.ts
            - -e
            - {{ .Values.abacus.runEnv }}
            envFrom:
            - secretRef:
                name: helloworld-kathy-secret
