apiVersion: batch/v1
kind: CronJob
metadata:
  name: helloworld-kathy
spec:
  schedule: {{ .Values.cronjob.schedule }}
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: helloworld-kathy
            image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
            imagePullPolicy: IfNotPresent
            command:
            - ./node_modules/.bin/ts-node
            - ./typescript/infra/scripts/helloworld/kathy.ts
            - -e
            - {{ .Values.abacus.runEnv }}
            envFrom:
            - secretRef:
                name: helloworld-kathy-secret
            env:
            - name: CHAINS_TO_SKIP
              value: {{ join "," .Values.chainsToSkip }}

