apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: helloworld-kathy-external-secret
  labels:
    {{- include "abacus-agent.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ include "abacus-agent.cluster-secret-store.name" . }}
    kind: ClusterSecretStore
  refreshInterval: "1h"
  # The secret that will be created
  target:
    name: {{ include "abacus-agent.fullname" . }}-relayer-secret
    template:
      type: Opaque
      metadata:
        labels:
          {{- include "abacus-agent.labels" . | nindent 10 }}
        annotations:
          update-on-redeploy: "{{ now }}"
      data:
        GCP_SECRET_OVERRIDES_ENABLED: "true"
        GCP_SECRET_OVERRIDE_ABACUS_{{ .Values.abacus.runEnv | upper }}_KEY_DEPLOYER: {{ print "'{{ .signer_key | toString }}'" }}
{{/*
   * For each network, create an environment variable with the RPC endpoint.
   * The templating of external-secrets will use the data section below to know how
   * to replace the correct value in the created secret.
   */}}
        {{- range .Values.abacus.chains }}
        GCP_SECRET_OVERRIDE_{{ .name | upper }}_RPC_ENDPOINT_{{ .name }}: {{ printf "'{{ .%s_rpc | toString }}'" .name }}
        {{- end }}
  data:
  - secretKey: signer_key
    remoteRef:
      key: {{ printf "abacus-%s-key-deployer" .Values.abacus.runEnv }}
      property: privateKey
{{/*
   * For each network, load the secret in GCP secret manager with the form: environment-rpc-endpoint-network,
   * and associate it with the secret key networkname_rpc.
   */}}
  {{- range .Values.abacus.chains }}
  - secretKey: {{ printf "%s_rpc" .name }}
    remoteRef:
      key: {{ printf "%s-rpc-endpoint-%s" $.Values.abacus.runEnv .name }}
  {{- end }}
