apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{.Release.Name}}-external-secret
  labels:
    {{- include "monitor.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ include "monitor.cluster-secret-store.name" . }}
    kind: ClusterSecretStore
  refreshInterval: "1h"
  # The secret that will be created
  target:
    name: {{.Release.Name}}-secret
    template:
      type: Opaque
      metadata:
        labels:
          {{- include "monitor.labels" . | nindent 10 }}
      data:
        .env: |-
          ENVIRONMENT={{ .Values.monitor.environment }}
{{ range $network := .Values.monitor.networks }}
{{ printf "%s_RPC='{{ .%s_rpc }}'" (upper $network) $network | indent 10 }}
{{- end }}
  data:
{{ range $network := .Values.monitor.networks }}
  - secretKey: {{ printf "%s_rpc" $network }}
    remoteRef:
      key: {{ printf "%s-rpc-endpoint-%s" $.Values.monitor.environment $network }}
{{- end }}