[package]
name = "run-locally"
version = "0.1.0"
edition = "2021"

[dependencies]
ctrlc = "3.2"
tempfile = "3.3"
maplit = "1.0"
nix = { version = "0.24", default-features = false, features = ["signal"] }
reqwest = { version = "0.11", default-features = false, features = ["blocking"] }
