name: Node
inputs:
  runneros:
    required: true
    default: 'test'

runs:
  using: "composite"
  steps:
    # Print inputs
    - name: Print inputs
      shell: bash
      run: |
        ls
        echo ${{ inputs.runneros }}
        cat runneros.txt 
