cargo-features = ["edition2021"]

[workspace]

members = [
    "abacus-core",
    "abacus-base",
    "abacus-cli",
    "abacus-test",
    "chains/abacus-ethereum",
    "agents/kathy",
    "agents/validator",
    "agents/relayer",
    "ethers-prometheus",
    "utils/loop-control"
]
