cargo-features = ["edition2021"]

[workspace]

members = [
    "abacus-core",
    "abacus-base",
    "abacus-test",
    "chains/abacus-ethereum",
    "agents/kathy",
    "agents/checkpointer",
    "agents/validator",
    "agents/relayer",
    "tools/kms-cli",
    "tools/abacus-cli",
    "tools/balance-exporter",
    "ethers-prometheus"
]
