[package]
name = "balance-exporter"
version = "0.1.0"
edition = "2021"
description = "Polls chains for optics contract wallet balances and reports them in OpenMetrics format"
authors = ["ember arlynx <ember.arlynx@clabs.co>"]
license = "Apache-2.0"

[dependencies]
tokio = "1"
futures = "0.3"

metrics = "0.18"
serde_json = "1.0"
serde = "1.0"
color-eyre = "0.6"
clap = { version = "3.1", features = ["cargo", "derive"] }
human-panic = "1.0"

abacus-base = { path = "../../abacus-base" }

# SMELL: reaching into the implementation details. abstract eventually.
abacus-ethereum = { path = "../../chains/abacus-ethereum" }
