{{- if .Values.abacus.validator.enabled }}
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ include "abacus-agent.fullname" . }}-validator-external-secret
  labels:
    {{- include "abacus-agent.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ include "abacus-agent.cluster-secret-store.name" . }}
    kind: ClusterSecretStore
  refreshInterval: "1h"
  # The secret that will be created
  target:
    name: {{ include "abacus-agent.fullname" . }}-validator-secret
    template:
      type: Opaque
      metadata:
        labels:
          {{- include "abacus-agent.labels" . | nindent 10 }}
      data:
{{ $index := 0 }}
{{- range .Values.abacus.validator.configs }}
        validator-{{ $index }}.env: |
          OPT_VALIDATOR_VALIDATOR_TYPE="hexKey"
          OPT_VALIDATOR_VALIDATOR_KEY={{ printf "'{{ .signer_key_%d | toString }}'" $index }}
{{ $index = add1 $index }}
{{- end }}
  data:
{{ $index := 0 }}
{{- range .Values.abacus.validator.configs }}
  - secretKey: signer_key_{{ $index }}
    remoteRef:
      key: {{ printf "abacus-%s-key-%s-validator-%d" $.Values.abacus.runEnv $.Values.abacus.outboxChain.name $index }}
      property: privateKey
{{ $index = add1 $index }}
{{- end }}
{{- end }}
