{{- if .Values.abacus.validator.enabled }}
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ include "abacus-agent.fullname" . }}-validator-external-secret
  labels:
    {{- include "abacus-agent.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ include "abacus-agent.cluster-secret-store.name" . }}
    kind: ClusterSecretStore
  refreshInterval: "1h"
  # The secret that will be created
  target:
    name: {{ include "abacus-agent.fullname" . }}-validator-secret
    template:
      type: Opaque
      metadata:
        labels:
          {{- include "abacus-agent.labels" . | nindent 10 }}
      data:
        {{- if not (hasKey .Values.abacus.validator.signer "aws") }}
        OPT_BASE_VALIDATOR_TYPE: "hexKey"
        OPT_BASE_VALIDATOR_KEY: {{ print "'{{ .signer_key | toString }}'" }}
        {{- end }}
  data:
  {{- if not (hasKey .Values.abacus.validator.signer "aws") }}
  - secretKey: signer_key
    remoteRef:
      key: {{ printf "%s-validator-signer-%s" .Values.abacus.runEnv .Values.abacus.outboxChain.name }}
      property: privateKey
  {{- end }}
{{- end }}