image:
  repository: gcr.io/abacus-labs-dev/abacus-monorepo
  tag:
abacus:
  runEnv: testnet2
  chains: []
cronjob:
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
externalSecrets:
  clusterSecretStore:
