apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: relayer-funder-addresses-external-secret
  labels:
    {{- include "abacus.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ include "abacus.cluster-secret-store.name" . }}
    kind: ClusterSecretStore
  refreshInterval: "1h"
  # The secret that will be created
  target:
    name: relayer-funder-addresses-secret
    template:
      type: Opaque
      metadata:
        labels:
          {{- include "abacus.labels" . | nindent 10 }}
        annotations:
          update-on-redeploy: "{{ now }}"
      data:
{{- range .Values.abacus.contextsToFund }}
        {{ . }}-addresses.json: {{ printf "'{{ .%s_addresses | toString }}'" . }}
{{- end }}
  data:
{{- range .Values.abacus.contextsToFund }}
  - secretKey: {{ . }}_addresses
    remoteRef:
      key: {{ printf "%s-%s-key-addresses" . $.Values.abacus.runEnv }}
{{- end }}