apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: relayer-funder-external-secret
  labels:
    {{- include "abacus.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ include "abacus.cluster-secret-store.name" . }}
    kind: ClusterSecretStore
  refreshInterval: "1h"
  # The secret that will be created
  target:
    name: relayer-funder-secret
    template:
      type: Opaque
      metadata:
        labels:
          {{- include "abacus.labels" . | nindent 10 }}
        annotations:
          update-on-redeploy: "{{ now }}"
      data:
        addresses.json: {{ print "'{{ .addresses | toString }}'" }}
  data:
  - secretKey: deployer_key
    remoteRef:
      key: {{ printf "abacus-%s-key-addresses" .Values.abacus.runEnv }}
