name: npm install
inputs:
  runneros:
    required: true
    default: 'test'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2

    - name: Print inputs
      shell: bash
      run: |
        echo ${{ inputs.runneros }}

    # Save caches individually
    - name: Parent Cache
      id: parent-cache
      uses: actions/cache@v2
      with:
        path: .//node_modules
        key: ${{ inputs.runneros }}-core-cache-${{ hashFiles('./package-lock.json') }}

    # Check out the lockfile from main, install, and then
    # verify the lockfile matches what was committed.
    - name: Install Parent
      shell: bash
      run: |
        git checkout main -- package-lock.json
        npm i
        CHANGES=$(git status -s)
        if [[ ! -z $CHANGES ]]; then
          echo "Changes found: $CHANGES"
          exit 1
        fi
