name: e2e

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

defaults:
  run:
    working-directory: ./rust

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - uses: Swatinem/rust-cache@v1
        with:
          working-directory: ./rust
      - run: cargo build --release --project run-locally
      - run: ./target/release/run-locally
        env:
          E2E_CI_MODE: 'true'
          E2E_CI_TIMEOUT_SEC: '300'
          E2E_KATHY_ROUNDS: '4'
