name: Node Cache

on:
  # Allows other workflows to call this one
  workflow_call:

jobs:
  checkout:
    runs-on: ubuntu-latest
    uses: actions/checkout@v2
  cache:
    runs-on: ubuntu-latest
    needs: [checkout]
    uses: actions/cache@v2
    steps:

      # Get caches
      - name: Core Cache
        id: core-cache
        with:
          path: ./solidity/optics-core/node_modules
          key: ${{ runner.os }}-core-cache-${{ hashFiles('solidity/optics-core/package-lock.json') }}

      - name: XApps Cache
        id: xapps-cache
        with:
          path: ./solidity/optics-xapps/node_modules
          key: ${{ runner.os }}-xapps-cache-${{ hashFiles('solidity/optics-xapps/package-lock.json') }}

      - name: Tests Cache
        id: tests-cache
        with:
          path: ./typescript/optics-tests/node_modules
          key: ${{ runner.os }}-tests-cache-${{ hashFiles('typescript/optics-tests/package-lock.json') }}

      - name: Deploy Cache
        id: deploy-cache
        with:
          path: ./typescript/optics-deploy/node_modules
          key: ${{ runner.os }}-deploy-cache-${{ hashFiles('typescript/optics-deploy/package-lock.json') }}

      - name: Typechain Cache
        id: typechain-cache
        with:
          path: ./typescript/typechain/node_modules
          key: ${{ runner.os }}-typechain-cache-${{ hashFiles('typescript/typechain/package-lock.json') }}

      - name: Provider Cache
        id: provider-cache
        with:
          path: ./typescript/optics-provider/node_modules
          key: ${{ runner.os }}-provider-cache-${{ hashFiles('typescript/optics-provider/package-lock.json') }}
