name: Node Install

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allows other workflows to call this one
  workflow_call:

jobs:
  checkout:
    runs-on: ubuntu-latest
    uses: actions/checkout@v2
  cache:
    runs-on: ubuntu-latest
    needs: [checkout]
    uses: .github/workflows/node-cache.yml
  install:
    runs-on: ubuntu-latest
    needs: [cache]
    steps:
      # Install separately depending on cache hit
      - name: Install Core
        if: steps.core-cache.outputs.cache-hit != 'true'
        run: cd ./solidity/optics-core && npm i

      - name: Install XApps
        if: steps.xapps-cache.outputs.cache-hit != 'true'
        run: cd ./solidity/optics-xapps && npm i

      - name: Install Tests
        if: steps.tests-cache.outputs.cache-hit != 'true'
        run: cd ./typescript/optics-tests && npm i

      - name: Install Deploy
        if: steps.deploy-cache.outputs.cache-hit != 'true'
        run: cd ./typescript/optics-deploy && npm i

      - name: Install Typechain
        if: steps.typechain-cache.outputs.cache-hit != 'true'
        run: cd ./typescript/typechain && npm i

      - name: Install Multi-Provider
        if: steps.provider-cache.outputs.cache-hit != 'true'
        run: cd ./typescript/optics-provider && npm i
