name: rust

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - 'rust/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required" '

  test:
    runs-on: ubuntu-latest

    steps:
      - run: 'echo "No test required" '

  lint:
    runs-on: ubuntu-latest

    steps:
      - run: 'echo "No lint required" '
