name: rust

on:
  pull_request:
    branches: [main]
    paths:
      - '*/**'
      - '!rust/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build-rs:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required" '

  test-rs:
    runs-on: ubuntu-latest

    steps:
      - run: 'echo "No test required" '

  lint-rs:
    runs-on: ubuntu-latest

    steps:
      - run: 'echo "No lint required" '
