name: Solidity

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: .github/workflows/node-install.yml
  lint:
    runs-on: ubuntu-latest
    needs: [install]

    steps:
      - uses: actions/checkout@v2
      - uses: .github/workflows/node-cache.yml

      # Lint
      - name: Lint
        run: |
          cd ./solidity/optics-core
          npm run lint
          cd ../optics-xapps
          npm run lint

      - name: Prettier
        run: |
          cd ./solidity/optics-core
          npm run prettier
          cd ../optics-xapps
          npm run prettier

  solidity-test:
    env:
      ETHERSCAN_API_KEY: ""

    runs-on: ubuntu-latest
    needs: [install]

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/node-cache.yml

      # Test
      - name: Test
        run: ./scripts/test-solidity.sh
