name: Solidity

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  checkout:
    runs-on: ubuntu-latest
    uses: actions/checkout@v2
  lint:
    runs-on: ubuntu-latest
    needs: [checkout]

    steps:
      # Lint
      - name: Lint
        run: |
          cd ./solidity/optics-core
          npm run lint
          cd ../optics-xapps
          npm run lint

      - name: Prettier
        run: |
          cd ./solidity/optics-core
          npm run prettier
          cd ../optics-xapps
          npm run prettier

  solidity-test:
    env:
      ETHERSCAN_API_KEY: ""

    runs-on: ubuntu-latest
    needs: [checkout]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache
        uses: ./.github/workflows/node-cache.yml

      # Test
      - name: Test
        run: ./scripts/test-solidity.sh
